### ISSUE TITLE
Build errors during inference

### ISSUE THREAD

**Issue by NishantPrabhuFujitsu** [Fugaku-LLM/DeepSpeedFugaku#2]
I am trying to fine-tune a GPT model using the default configuration in `run_pretrain_gpt_fugaku.sh`, but I encounter the following issues while doing so (please see Setup and Python environment info below for context).

**1. If I run the script as-is**: I get the following error, indicating a certain `--local-rank` argument not being recognized by `pretrain_gpt.py`. I don't see this argument getting passed in the shell script. Full error trace: 
[torch_dist_error.txt](https://github.com/user-attachments/files/15756956/torch_dist_error.txt)

**2. If I comment out torch.distributed.launch, running only on one process:** The script attempts to build `deepspeed_shm_comm` and fails. Full error trace: 
[no_torch_dist_error.txt](https://github.com/user-attachments/files/15756961/no_torch_dist_error.txt)

**3. If I run the script on a GPU instance:** The code errors out when attempting to import `helpers` from `megatron.data`, which happens to be a C++ file. Full error trace: 
[gpu_error.txt](https://github.com/user-attachments/files/15756962/gpu_error.txt)

### Setup
- Downloaded the `gpt2_345m` checkpoint and `gpt2-merges.txt` and `gpt2-vocab.json` using the scripts in `dataset/`.
- Converted the `databricks/databricks-dolly-15k` dataset from huggingface into the required JSON format and convert them into `.bin` and `.idx` files using `tools/preprocess_data.py`.
- Updated the following lines in `run_pretrain_gpt_fugaku.sh`:
    - commented line 26: `# source /data/hp190122/share/PyTorch-1.10.1/env.src`
    - `CHECKPOINT_PATH`
    - `DATA_PATH`

### Python environment info
```
Package            Version
------------------ -----------
aiohttp            3.9.5
aiosignal          1.3.1
annotated-types    0.7.0
attrs              23.2.0
certifi            2024.6.2
charset-normalizer 3.3.2
click              8.1.7
datasets           2.19.2
deepspeed          0.14.2
dill               0.3.8
docker-pycreds     0.4.0
filelock           3.14.0
frozenlist         1.4.1
fsspec             2024.3.1
gitdb              4.0.11
GitPython          3.1.43
hjson              3.1.0
huggingface-hub    0.23.3
idna               3.7
Jinja2             3.1.4
joblib             1.4.2
MarkupSafe         2.1.5
mpmath             1.3.0
multidict          6.0.5
multiprocess       0.70.16
networkx           3.3
ninja              1.11.1.1
nltk               3.8.1
numpy              1.26.4
packaging          24.1
pandas             2.2.2
pip                24.0
platformdirs       4.2.2
protobuf           5.27.1
psutil             5.9.8
py-cpuinfo         9.0.0
pyarrow            16.1.0
pyarrow-hotfix     0.6
pydantic           2.7.3
pydantic_core      2.18.4
pynvml             11.5.0
python-dateutil    2.9.0.post0
pytz               2024.1
PyYAML             6.0.1
regex              2024.5.15
requests           2.32.3
sentencepiece      0.2.0
sentry-sdk         2.5.1
setproctitle       1.3.3
setuptools         65.5.0
six                1.16.0
smmap              5.0.1
sympy              1.12.1
torch              2.3.1
tqdm               4.66.4
typing_extensions  4.12.2
tzdata             2024.1
urllib3            2.2.1
wandb              0.17.1
xxhash             3.4.1
yarl               1.9.4
```

**Comment by m-ymzk** [comment]
Welcome to this repository.
This repository is optimized to run on Fugaku with a large number of A64FX CPU nodes and does not care for other environments.

If you want to train on a GPU server, please refer to the original DeepSpeed and/or Megatron-LM repositories.

**Comment by NishantPrabhuFujitsu** [comment]
Understood. Thank you for your time.
