### ISSUE TITLE
Request for Access to Specific Dynamic Libraries

### ISSUE THREAD

**Issue by CaRoLZhangxy** [Fugaku-LLM/DeepSpeedFugaku#3]
I am currently working with the repository and have encountered an issue where some dynamic libraries are missing access permissions, such as pytorch and Allreduce lib listed in the scripts. I am trying to apply some training acceleration techniques on this project, so these libraries are essential. Is there any possible way I can gain access to these dynamic libraries or source code?Thank you very much for your attention to this matter.

**Comment by m-ymzk** [comment]
Thank you for your question on this repository.

The pytorch we used was customized for the A64FX CPU from the Fujitsu repository.
Also, there is no plan to release the source code for allreduce optimization specialized for TOFU network of Fugaku.
So it would be good to use the pytorch environment that is best suited for each CPU and GPU.

Ref. https://github.com/fujitsu/pytorch/tree/r1.13_for_a64fx

**Comment by CaRoLZhangxy** [comment]
Got it. Thank you for your response!
